name: sast-secret

on:
  push:
    branches:
      - master
  pull_request:
      branches: [ master]

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        #continue-on-error: true 

  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Running Horusec Security Download latest version
        #continue-on-error: true
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" --config-file-path horusec-config.json    

      - name: Upload  security scan result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: horusec
          path: horusec-config.json  
